### ISSUE TITLE
malformed dataset

### ISSUE THREAD

**Issue by ambuc** [ambuc/test-of-time#6]
I know the dataset is tricky, but there are a couple of really simple improvements that need to be made. 

One is the way it displays quotes - currently it will print `foo` as `quotfooquot`. The stray `quot`s could be removed or replaced by proper quotes — either one is fine.

The other is that one in every twenty or so events will be extraordinarily long — like, several paragraphs. Just a length filter could solve this — exclude any events longer than, say, three sentences. Could make the game easier.

**Comment by jsrmath** [comment]
Now that people are actually playing this, yes, I should probably put more than like half an hour into making the data good.  The "quot" thing is tricky, because if I just remove all instances of "quot," that will turn things like "quote" or "quotation" into "e" and "ation", rendering the question a lot less readable.  Since there is sooo much data, we might just want to string anything that has a "quot" in it.  This won't get rid of everything that has a quotation, only the ones that are malformed (most of them are ampquot which is already being corrected for).

I think a length maximum is a good idea.  I'm gonna set it at 140 characters (Tweet length).  I'll make these changes and PR.
